[[data]]
"सङ्ग्रहः" = 'ऋग्वेदस्य शकल-संहिता'
"मन्त्राः /श्लोकाः" = 10552
"उच्चारणावधिः (निमेषाणि)" = 2560
"टिप्पणिः" = '~ आश्वलायनसंहिता'

[[data]]
"सङ्ग्रहः" = 'ऋग्वेदस्य शाङ्खायन-संहिता'

[[data]]
"सङ्ग्रहः" = 'शुक्ल-यजुर्वेदस्य माध्यन्दिन-संहिता'
"मन्त्राः /श्लोकाः" = 1975
"उच्चारणावधिः (निमेषाणि)" = 600
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 24

[[data]]
"सङ्ग्रहः" = 'शुक्ल-यजुर्वेदस्य काण्व-संहिता'
"मन्त्राः /श्लोकाः" = 2086
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 24

[[data]]
"सङ्ग्रहः" = 'कृष्ण-यजुर्वेदस्य तैत्तिरीय-संहिता'
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 42

[[data]]
"सङ्ग्रहः" = 'कृष्ण-यजुर्वेदस्य तैत्तिरीय-संहिता (मन्त्रभागमात्रम्)'
"मन्त्राः /श्लोकाः" = 1945
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 24
"टिप्पणिः" = 'https://docs.google.com/spreadsheets/d/1xFXhg__yitgiECypnO5KAc9Xbe8cTzt-9dZD3AqpmtU/edit#gid=0'

[[data]]
"सङ्ग्रहः" = 'कृष्ण-यजुर्वेदस्य तैत्तिरीय-शाखाया आपस्तम्ब+एकाग्निकाण्डम्'

[[data]]
"सङ्ग्रहः" = 'कृष्ण-यजुर्वेदस्य कठक/चरक-संहिता'
"मन्त्राः /श्लोकाः" = 3093

[[data]]
"सङ्ग्रहः" = 'सामवेदस्य कौथुम-संहिता'
"मन्त्राः /श्लोकाः" = 1875
"उच्चारणावधिः (निमेषाणि)" = 2560

[[data]]
"सङ्ग्रहः" = 'सामवेदस्य राणायनीय-संहिता'

[[data]]
"सङ्ग्रहः" = 'अथर्ववेदस्य शौनक-संहिता'
"मन्त्राः /श्लोकाः" = 5977

[[data]]
"सङ्ग्रहः" = 'अथर्ववेदस्य पैप्पलाद-संहिता'
"मन्त्राः /श्लोकाः" = 7899

[[data]]
"सङ्ग्रहः" = 'बौधायनोक्त+उदकशान्तिमन्त्राः'
"मन्त्राः /श्लोकाः" = 200
"उच्चारणावधिः (निमेषाणि)" = 106

[[data]]
"सङ्ग्रहः" = 'विष्णुसहस्रनामस्तोत्रम्'
"मन्त्राः /श्लोकाः" = 108

[[data]]
"सङ्ग्रहः" = 'दुर्गा-सप्तशती'
"मन्त्राः /श्लोकाः" = 700

[[data]]
"सङ्ग्रहः" = 'भगवद्गीता'
"मन्त्राः /श्लोकाः" = 700

[[data]]
"सङ्ग्रहः" = 'अष्टाध्यायी'
"मन्त्राः /श्लोकाः" = 4000
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 4

[[data]]
"सङ्ग्रहः" = 'अमरकोशः'
"मन्त्राः /श्लोकाः" = 1563

[[data]]
"सङ्ग्रहः" = 'द्राविड-दिव्य-प्रबन्धः'
"मन्त्राः /श्लोकाः" = 4000

[[data]]
"सङ्ग्रहः" = 'तिरुक्कुरळ्'
"मन्त्राः /श्लोकाः" = 1330
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 3

[[data]]
"सङ्ग्रहः" = 'तिरुमुरै'
"मन्त्राः /श्लोकाः" = 1469

[[data]]
"सङ्ग्रहः" = 'Quran-उन्मादग्रन्थः'
"मन्त्राः /श्लोकाः" = 6226
"उच्चारणावधिः (निमेषाणि)" = 600
"कण्ठस्थीकरणाय+ अपेक्षितोऽवधिः (मासाः)" = 36

[[data]]
"सङ्ग्रहः" = 'महाभारतम्'
"मन्त्राः /श्लोकाः" = 100000
